//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public string Explanation { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> OnSale { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    }
}
