//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int UserAddressID { get; set; }
        public Nullable<int> AdressTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual User User { get; set; }
    }
}
